### ISSUE TITLE
spelling/grammar

### ISSUE THREAD

**Issue by brayton94** [flythereddflagg/python_book#4]
https://github.com/flythereddflagg/python_book/blob/master/markdown/01-Intro%20and%20How%20to%20Use%20This%20Book.md#sections
In each section of this book **thing** will be ordered by how mandatory they are. If you wish to move as quickly as possible, you may only do the first part of each section where I will cover the essential material. However, I do recommend doing all parts of every section to get the most out of this book as well as to hone your skills.

**Comment by brayton94** [comment]
**In 1984 film** "The Karate Kid", Mr. Miyagi, the teacher, doesn't start training Daniel, the protagonist, in Karate by teaching him fancy moves but begins by having him perform many menial tasks with no apparent point to them.

**Comment by brayton94** [comment]
**Understand when things get boring or tedious remember the Karate Kid.** 

Rephrase, grammar.

**Comment by brayton94** [comment]
I am asking for some faith from you right now but trust that if you learn to code without an IDE you will learn better than any of your peers that use **and** IDE.

I think you can break this into two sentences or use a comma.

**Comment by flythereddflagg** [comment]
Fixed all these mistakes. If you have more edits open a new issue.
